### PR TITLE
Add support for HTTP Basic auth

### PR DESCRIPTION
**Pull request by mce35**
There was a change recently in Domoticz auth, now giving username/password in the URL is not working anymore. HTTP Basic auth may still be used if enable in Domoticz configuration.

This PR adds the possibility to use HTTP Basic auth by adding a new settings ```auth_mode```:
```php
config['auth_mode'] = 'basic'; // use HTTP Basic auth
config['auth_mode'] = 'url';   // set username/password encoded in the URL (default if not set)
```

### CODE REVIEW

**Comment by lokonli** [comment]
Thanks!
I'll do some tests and merge this weekend.

**Comment by lokonli** [comment]
The mechanism is working, thanks.

I prefer to auto detect the authentication method.
I think we can switch to basic auth from Domoticz version 2022.2, build 15012 (?) onwards.

Dashticz already contains some mechanism to configure the settings based on the Domoticz version, so that can be reused.

See version.js, line 129

I can make these changes, but if you could do that it would be great.

**Comment by lokonli** [comment]
I have some time now. I'll make the changes myself.

**Comment by mce35** [comment]
> The mechanism is working, thanks.
> 
> I prefer to auto detect the authentication method. I think we can switch to basic auth from Domoticz version 2022.2, build 15012 (?) onwards.
> 
> Dashticz already contains some mechanism to configure the settings based on the Domoticz version, so that can be reused.
> 
> See version.js, line 129
> 
> I can make these changes, but if you could do that it would be great.

From the [doc](https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s#Authorization) it was remove in 2022.2 build 14708.

**Comment by mce35** [comment]
> I have some time now. I'll make the changes myself.

I just pushed the changes.

**Comment by lokonli** [comment]
Thanks!

**Pull request merged**
