### PR TITLE
Onegraph

### PR DESCRIPTION
**Pull request by lokonli**

### CODE REVIEW

**Comment by lokonli** [comment]
@clinkadink : Did you delete the documentation images on purpose?

**Comment by clinkadink** [comment]
No. I did see some on my GitHub desktop. Maybe I did something wrong. But it was unintentional.

**Comment by lokonli** [comment]
I'll merge this PR into the websocket branch.

Then we have to restore multigraph[3-6].png after that. I'll take care of that.

The sliding=true in thermostat.js is not completely correct anymore. I changed that to sliding=idx in a previous commit. It prevents updating device idx while sliding.

I want to change this behavior anyway, so I'll make a fix for that later as well.

In my custom graph I use for testing, the title shows 'undefined'. I'll check that later on.

Except for these small remarks: excellent work!

**Comment by clinkadink** [comment]
Not sure what I did to those images. Sorry, still learning (pull, push, commit, bla, bla). I can code, but I am learning the dark art of release management.

Re thermostat. Yes, noticed there have been some changes. I checked row by row, so I wouldn't overwrite anything. Apologies, it was late.

Re graph undefined. The code takes the Name value of the device if it is an undefined graph, or uses the block title, if its defined. No real change their. I have 4 undefined graphs (e.g. graph_16) and it works fine. Weird.

Excellent work? Ha! I am sure my code doesn't come close to yours ;)

**Pull request merged**
